server:
  port: 8081
  servlet:
    context-path: /api/v1/local
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true